# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
data=load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X=data.data
y=data.target

In [6]:
#Chech feature values
X[0:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
#Check label values
y[0:5]

array([0, 0, 0, 0, 0])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
import numpy as np
import pandas as pd

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [11]:
#Check train check feature shape
X_train.shape

(112, 4)

In [12]:
#Check test feature shape
X_test.shape

(38, 4)

In [13]:
#Check test label shape
y_test.shape

(38,)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from sklearn.preprocessing import OneHotEncoder

In [0]:
enc=OneHotEncoder(handle_unknown='ignore',sparse=False)

In [0]:
#y.reshape(150,1)

In [17]:
enc.fit(y_train.reshape(112,1))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=False)

In [0]:
# transform test and train labels
y_train=enc.transform(y_train.reshape(112,1))
y_test=enc.transform(y_test.reshape(38,1))

In [19]:
# check fro transformation
y_train[0:5,:]

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [20]:
#Check categories
enc.categories_

[array([0, 1, 2])]

## Question 5

### Initialize a sequential model
- Define a sequential model

In [21]:
from keras.models import Sequential

Using TensorFlow backend.


In [0]:
model=tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
from keras.layers.core import Dense,Dropout,Activation,Flatten

In [0]:
# add input layer
model.add(tf.keras.layers.Dense(4,input_shape=(4,)))
# add output layer
model.add(tf.keras.layers.Dense(3,activation='softmax'))


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#compile the model
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])


## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [27]:
model.fit(X_train,y_train,nb_epoch=100,verbose=1,validation_data=(X_test,y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 5ms/sample - loss: 1.3572 - accuracy: 0.2500 - val_loss: 1.3533 - val_accuracy: 0.2368
Epoch 2/100
112/112 [==============================] - 0s 173us/sample - loss: 1.1808 - accuracy: 0.3661 - val_loss: 1.1977 - val_accuracy: 0.2368
Epoch 3/100
112/112 [==============================] - 0s 223us/sample - loss: 1.1165 - accuracy: 0.3661 - val_loss: 1.2069 - val_accuracy: 0.2368
Epoch 4/100
112/112 [==============================] - 0s 163us/sample - loss: 1.0749 - accuracy: 0.3661 - val_loss: 1.1024 - val_accuracy: 0.2368
Epoch 5/100
112/112 [==============================] - 0s 164us/sample - loss: 1.0467 - accuracy: 0.3661 - val_loss: 1.0923 - val_accuracy: 0.2368
Epoch 6/100
112/112 [==============================] - 0s 326us/sample - loss: 0.9969 - accuracy: 0.3661 - val_loss: 1.0598 - val_accuracy: 0.2368
Epoch 7/100
112/112 [==============================] - 0s 309us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_test_predicted=model.predict(X_test)

In [29]:
y_test_predicted[0]

array([0.00176347, 0.16883397, 0.82940257], dtype=float32)

In [30]:
y_test_predicted[0].argmax()

2

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [31]:
y_test[0]

array([0., 0., 1.])

In [32]:
y_test[0].argmax()

2

In [0]:
# both predicted and acutal class for test sample checked are same



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [35]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [38]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd


In [0]:
# read the file
df=pd.read_csv('/content/drive/My Drive/Colab Notebooks/prices.csv') 

In [73]:
# check for data upload
df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [74]:
# check data type
df.dtypes

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

In [75]:
#Check shape
df.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
# drop columns
df.drop(['date', 'symbol'],inplace=True,axis=1)

In [77]:
# data frame 
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
# select first 1000 rows 
df=df.iloc[:1000,:]

In [79]:
# check for selection
df.shape

(1000, 5)

In [80]:
# check dataframe
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
# select  features columns
X=df.iloc[:,0:4] 
# select label colums
y=df.iloc[:,-1]/1000000

In [82]:
# Check feature data
X.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [83]:
# check label columns
y.head()

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
import numpy as np

In [0]:
# convert feature to Numpy with data dtype float32
X=np.array(X,dtype=np.float32)

In [86]:
X

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

In [87]:
# check shape of feature
X.shape

(1000, 4)

In [88]:
# check data dtype
X.dtype


dtype('float32')

In [89]:
#convert features to tensor 
X=tf.Variable(X)
X

<tf.Variable 'Variable:0' shape=(1000, 4) dtype=float32, numpy=
array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)>

In [90]:
# Convert label to tensor
y=tf.Variable(y)
y=tf.cast(y,dtype=tf.float32)
y

<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([2.163600e+00, 2.386400e+00, 2.489500e+00, 2.006300e+00,
       1.408600e+00, 1.098000e+00, 9.496000e-01, 7.853000e-01,
       1.093700e+00, 1.523500e+00, 1.653900e+00, 9.443000e-01,
       7.449000e-01, 7.038000e-01, 5.631000e-01, 8.961000e-01,
       6.804000e-01, 7.499000e-01, 5.742000e-01, 6.948000e-01,
       8.963000e-01, 9.563000e-01, 9.971000e-01, 1.200500e+00,
       1.725200e+00, 1.946000e+00, 1.319500e+00, 9.224000e-01,
       1.185100e+00, 9.215000e-01, 4.409000e-01, 1.244300e+00,
       6.813000e-01, 4.112000e-01, 4.473000e-01, 5.592000e-01,
       4.599000e-01, 9.716000e-01, 6.941000e-01, 1.159600e+00,
       8.847000e-01, 6.920000e-01, 8.980000e-01, 8.445000e-01,
       7.965000e-01, 4.168000e-01, 5.902000e-01, 4.951000e-01,
       5.158000e-01, 5.621000e-01, 8.093000e-01, 1.607300e+00,
       1.001300e+00, 7.114000e-01, 4.442000e-01, 5.341000e-01,
       7.982000e-01, 5.910000e-01, 4.432000e-01, 5.780000e-01,
      

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
# normalize feature columns
X_norm=tf.math.l2_normalize(X,axis=None)

In [103]:
# check normalized data
X_norm

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
#Initialize weigth and bias with zeros
b=tf.Variable(tf.zeros(shape=(1)))
w=tf.Variable(tf.zeros(shape=(4,1)))


In [105]:
#check for initialization and weigths
print("w:", w)
print("b:", b)

w: <tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>
b: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
# define function for label prediction
def yhat(x,m,c):
  y_predicted=tf.add(tf.matmul(x,m),c)
  return y_predicted


### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
# define function for loss calculation
def loss_func(y_pred,y_act):
    error=tf.subtract(y_pred,y_act)
    loss=tf.reduce_mean(tf.square(error))
    return loss

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
# assign learing rate value
L=tf.constant(0.01)

In [109]:
L

<tf.Tensor: shape=(), dtype=float32, numpy=0.01>

In [0]:
# define  a function for optimization
def train_step(w,b,L,y,X_norm): 
    with tf.GradientTape(persistent=True) as tape:
      tape.watch([w,b]) 
      current_loss=loss_func(yhat(X_norm,w,b),y)
      # Calculate Gradients of Loss w.r.t weights and bia
      dw,db = tape.gradient(current_loss, [w,b])
      # Update Weights and Bias based on gradients
      w.assign_sub(L*dw)
      b.assign_sub(L*db)
     
     
   
   
    

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [111]:
epochs=tf.constant(100)
# Train the model for 100 epochs 
for epoch_count in range(epochs):
    real_loss = loss_func(y, yhat(X_norm,w,b))
    train_step( w,b, L,y,X_norm)
    print(f"Epoch count {epoch_count}: Loss value: {real_loss.numpy()}")




Epoch count 0: Loss value: 237.28665161132812
Epoch count 1: Loss value: 236.16758728027344
Epoch count 2: Loss value: 235.09298706054688
Epoch count 3: Loss value: 234.06101989746094
Epoch count 4: Loss value: 233.06997680664062
Epoch count 5: Loss value: 232.11781311035156
Epoch count 6: Loss value: 231.2038116455078
Epoch count 7: Loss value: 230.3258514404297
Epoch count 8: Loss value: 229.48265075683594
Epoch count 9: Loss value: 228.6729736328125
Epoch count 10: Loss value: 227.8953857421875
Epoch count 11: Loss value: 227.1483154296875
Epoch count 12: Loss value: 226.43113708496094
Epoch count 13: Loss value: 225.74234008789062
Epoch count 14: Loss value: 225.08079528808594
Epoch count 15: Loss value: 224.44552612304688
Epoch count 16: Loss value: 223.8350067138672
Epoch count 17: Loss value: 223.2493133544922
Epoch count 18: Loss value: 222.68655395507812
Epoch count 19: Loss value: 222.1459503173828
Epoch count 20: Loss value: 221.6268768310547
Epoch count 21: Loss value: 221.

### Observe values of Weight
- Print the updated values

In [112]:
w

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[0.0547828 ],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)>

In [113]:
# updated weight values
w.numpy()

array([[0.0547828 ],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [114]:
# updated bias values
b.numpy()

array([4.607657], dtype=float32)